using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraBars;
using System.Data.Entity;

namespace RadanMaster
{
    public partial class AllItems : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        RadanMaster.DAL.RadanMasterContext dbContext { get; set; }

        public AllItems()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            dbContext = new RadanMaster.DAL.RadanMasterContext();

            dbContext.OrderItems.Load();
            dbContext.Parts.Load();
            dbContext.Orders.Load();
            dbContext.Files.Load();
            dbContext.Operations.Load();

            gridControlAllItems.DataSource = dbContext.OrderItems.Local.ToBindingList();
        }
    }
}