using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraBars;
using System.IO;
using DevExpress.Utils;

namespace RadanMaster
{
    public partial class AllProduction : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        RadanMaster.DAL.RadanMasterContext dbContext { get; set; }
        RefreshHelper helper;

        public AllProduction()
        {
            InitializeComponent();
            dbContext = new RadanMaster.DAL.RadanMasterContext();

            entityServerModeSource2.QueryableSource = from orderitem in dbContext.OrderItems
                                                      select new
                                                      {
                                                          orderitem.ID,
                                                          orderitem.QtyRequired,
                                                          orderitem.QtyNested,
                                                          orderitem.Part.CategoryName,
                                                          orderitem.Part.FileName,
                                                          orderitem.Part.Description,
                                                          orderitem.Part.IsStock,
                                                          orderitem.Part.Thickness,
                                                          orderitem.Order.OrderNumber,
                                                          orderitem.Part.StructuralCode,
                                                          orderitem.Part.Operations.FirstOrDefault().Name,
                                                          orderitem.Order.ScheduleName,
                                                          orderitem.Order.BatchName,
                                                          orderitem.Notes,
                                                          orderitem.Order.IsComplete,
                                                          orderitem.Order.IsBatch
                                                      };
            // load grid layout from file
            string SettingsFilePath = new FileInfo(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)) + @"\RadanMaster\AllProductionGridLayout.xml";
            if (System.IO.File.Exists(SettingsFilePath))
            {
                gridControlAllProduction.ForceInitialize();
                gridControlAllProduction.MainView.RestoreLayoutFromXml(SettingsFilePath);
            }

            // load collapsed/expanded state of gridview
            helper = new RefreshHelper(gridViewAllProduction, "ID", "AllProductionGridExpansion.xml");
            helper.LoadViewInfo();
            // This line of code is generated by Data Source Configuration Wizard
            //entityServerModeSource2.QueryableSource = new RadanMaster.DAL.RadanMasterContext().OrderItems;
        }

        private void AllProduction_FormClosing(object sender, FormClosingEventArgs e)
        {
            string SettingsFilePath = new FileInfo(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)) + @"\RadanMaster\AllProductionGridLayout.xml";
            gridControlAllProduction.MainView.SaveLayoutToXml(SettingsFilePath, OptionsLayoutBase.FullLayout);

            //save the expanded/contracted state of grouped rows
            helper.SaveViewInfo();
        }
    }
}