using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace RadanMaster
{
    public partial class TestForm : Form
    {
        RadanMaster.DAL.RadanMasterContext dbContext { get; set; }

        public TestForm()
        {
            InitializeComponent();
            dbContext = new RadanMaster.DAL.RadanMasterContext();
            // This line of code is generated by Data Source Configuration Wizard
            //entityServerModeSource1.QueryableSource = new RadanMaster.DAL.RadanMasterContext().OrderItems;

            entityServerModeSource1.QueryableSource = from orderitem in dbContext.OrderItems
                                                      select new
                                                      {
                                                          orderitem.ID,
                                                          orderitem.QtyRequired,
                                                          orderitem.QtyNested,
                                                          orderitem.Part.CategoryName,
                                                          orderitem.Part.FileName,
                                                          orderitem.Part.Description,
                                                          orderitem.Part.IsStock,
                                                          orderitem.Part.Thickness,
                                                          orderitem.Order.OrderNumber,
                                                          orderitem.Part.StructuralCode,
                                                          orderitem.Part.Operations.FirstOrDefault().Name,
                                                          orderitem.Order.ScheduleName,
                                                          orderitem.Order.BatchName,
                                                          orderitem.Notes,
                                                          orderitem.Order.IsComplete,
                                                          orderitem.Order.IsBatch
                                                      };

            //entityServerModeSource1.QueryableSource = from orderitem in dbContext.OrderItems
            //                                          select new
            //                                          {
            //                                              orderitem.ID,
            //                                              orderitem.QtyRequired,
            //                                              orderitem.QtyNested

            //                                          };
        }
    }
}
